name: Deploy Static Website to GitHub Pages

on:
  # Runs on pushes to the default branch (main)
  push:
    branches: ["main"]

  # Allows you to trigger the workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, keeping previous runs that are in-progress
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Pages (prepare for deploying to GitHub Pages)
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload the static files for GitHub Pages deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the directory where your static site is located
          # Adjust this if your static files are in a subfolder like `/dist`
          path: './'  # Assuming files are in the root, if not specify the correct directory, e.g., './dist'

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
